[Backport to 21] fixes a new validation failure in a UniformId test (… (#3492)
…#3301)

A recent spirv-val change requires that OpDecorateId IDs are
well-ordered, which means that the decoration operand ID cannot be the
same as the decoration target ID. See:
https://github.com/KhronosGroup/SPIRV-Tools/pull/6227

This leads to the failure:

```
error: line 6: Parameter <ID> '2[%uint_0]' must appear earlier in the binary than the target
  OpDecorateId %uint_0 UniformId %uint_0
```

The fix is to use a different ID for the decoration operand and the
decoration target.

Co-authored-by: Ben Ashbaugh <ben.ashbaugh@intel.com>